/** @type {import('tailwindcss').Config} */
// Màu sắc / typography / bo góc lấy nguyên từ
// ../stitch_cupid_agent_ai_analysis/DESIGN.md (Google Stitch design system cho Cupid Agent)
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#f7f9ff",
        "surface-dim": "#d7dadf",
        "surface-bright": "#f7f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f4f9",
        "surface-container": "#ebeef3",
        "surface-container-high": "#e5e8ee",
        "surface-container-highest": "#e0e3e8",
        "on-surface": "#181c20",
        "on-surface-variant": "#5a4042",
        "inverse-surface": "#2d3135",
        "inverse-on-surface": "#eef1f6",
        outline: "#8e6f71",
        "outline-variant": "#e2bec0",
        "surface-tint": "#ba1340",
        primary: "#b60e3d",
        "on-primary": "#ffffff",
        "primary-container": "#da3054",
        "on-primary-container": "#fffbff",
        "inverse-primary": "#ffb2b8",
        secondary: "#8433c4",
        "on-secondary": "#ffffff",
        "secondary-container": "#bd6efe",
        "on-secondary-container": "#450073",
        tertiary: "#5a5c5c",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#737575",
        "on-tertiary-container": "#fcfcfc",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdadb",
        "primary-fixed-dim": "#ffb2b8",
        "on-primary-fixed": "#40000f",
        "on-primary-fixed-variant": "#91002d",
        "secondary-fixed": "#f2daff",
        "secondary-fixed-dim": "#e0b6ff",
        "on-secondary-fixed": "#2e004e",
        "on-secondary-fixed-variant": "#6a0baa",
        "tertiary-fixed": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary-fixed-variant": "#454747",
        background: "#f7f9ff",
        "on-background": "#181c20",
        "surface-variant": "#e0e3e8",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        // Cùng tên token với fontSize để dùng được cặp class "text-body-md font-body-md"
        // y hệt markup Stitch gốc.
        "headline-xl": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
      },
      maxWidth: {
        container: "1200px",
      },
      spacing: {
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
      },
    },
  },
  plugins: [],
};
